const fs = require("fs");
const json = JSON.parse(fs.readFileSync("./app.json", "utf8"));

const output = `// This file is automatically generated from app.json by scripts/generate-config.js
// Do not edit this file directly.
export const APP_CONFIG = ${JSON.stringify(json)};`;

fs.writeFileSync("./app-config.js", output);

console.log("✅ app-config.js generated from app.json");
